spring.application.name=gestion_profesion


# ========== DATASOURCE (CONEXIÓN BD) ==========
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_profesion
spring.datasource.username=campus2023
spring.datasource.password=campus2023
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA/HIBERNATE ==========
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========== PUERTO ==========
server.port=8080

# ========== LOGGING ==========
logging.level.root=INFO
logging.level.com.s1.gestion_profesion=DEBUG

# ========== SPRINGDOC / SWAGGER ==========
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
